### ISSUE TITLE
Activities reporting system

### ISSUE THREAD

**Issue by tratteo** [Siamango/Solmango#5]
Implement a reporting system for activities. 
Guidelines:
- The report should include the date of the activity, the type of the activity performed and the activity data
- Each activity has its own data
- There is no need to deserialize and load into memory the reports, thus there is no need for a representative class
- The serialization must be a preference that can be disabled in the options, therefore, add a field in the [PreferencesOptions](https://github.com/Siamango/Solmango/blob/main/SolmangoDAO/Source/Dao/Options/Options.Preferences.cs) and execute the report serialization only if the option (bool) is enabled

Report workflow:
- Create an abstract method in [DecentralizedActivity](https://github.com/Siamango/Solmango/blob/main/SolmangoDAO/Source/Dao/DecentralizedActivities/DecentralizedActivity.cs): ```string SerializeActivityData()```. This method should return the activity data in a json formatted string (look the class [Messages](https://github.com/Siamango/Solmango/blob/main/SolmangoDAO/Source/Messages.cs) to see how to build such formatted string).
- Each activity that inherits from DecentralizedActivity must implement the method.
- Simply retrieve and serialize to a file the activity report string when the activity is completed in the [ExecuteDAOActivity](https://github.com/Siamango/Solmango/blob/e9ee39dd259ddfd8e63c7400bca3facf1be687f1/SolmangoDAO/Source/Dao/DaoManager.cs#L183) function cycle

**Comment by Nickmadia** [comment]
everything done
